"""
ai/llm/provider.py
-------------------
LLM provider abstraction for clinical explanations.

DESIGN: The LLMProvider is an abstract base class. All providers implement
the same interface. Switching from OpenAI to a local LLM (e.g., Ollama) or
mock requires only changing the LLM_PROVIDER environment variable.

Providers:
  - MockProvider:   Returns deterministic explanations (default for demos)
  - OpenAIProvider: Calls GPT-4o-mini (requires OPENAI_API_KEY)
  - LocalProvider:  Calls Ollama or any OpenAI-compatible local server
"""
import json
import logging
from abc import ABC, abstractmethod
from typing import Dict, List, Optional

import httpx

from core.config.settings import get_settings

settings = get_settings()
logger = logging.getLogger(__name__)

DISCLAIMER = (
    "\n\n---\n"
    "⚕️ **Clinical Disclaimer**: This analysis is generated by an AI system "
    "to support clinical decision-making. It does not replace professional "
    "medical judgment. All findings must be reviewed and confirmed by a "
    "qualified healthcare professional."
)

CLINICAL_PROMPT_TEMPLATE = """You are a clinical decision support AI assisting a physician with pulmonary disease assessment.

Patient Information:
- Age: {age} years, Sex: {sex}
- Chief Complaint: {chief_complaint}
- Symptoms: {symptoms}
- Symptom Duration: {symptom_duration}
- Existing Conditions: {conditions}
- Current Medications: {medications}

Vital Signs:
- Temperature: {temperature}°C, SpO2: {spo2}%, Respiratory Rate: {rr}/min
- Pulse: {pulse} bpm, BP: {bp_sys}/{bp_dia} mmHg, BMI: {bmi}

AI Model Prediction (DenseNet121 Chest X-Ray Analysis):
- Predicted Diagnosis: {predicted_class}
- Confidence: {top_confidence:.1%}
- All Class Probabilities: {confidence_scores}

Provide a structured clinical explanation with:
1. DIAGNOSTIC EXPLANATION: Interpret the AI findings in context of the patient's presentation
2. SEVERITY ASSESSMENT: Rate severity as Low/Moderate/High/Critical with clinical justification
3. CLINICAL REASONING: Correlate imaging findings with symptoms and vitals
4. RECOMMENDED NEXT STEPS: List 3-5 specific clinical actions (investigations, treatments, referrals)

Keep the response professional, evidence-based, and suitable for a clinical report.
Respond in JSON format:
{{
  "explanation": "...",
  "severity": "Low|Moderate|High|Critical",
  "clinical_reasoning": "...",
  "recommendations": ["...", "...", "..."]
}}"""


class LLMProvider(ABC):
    """Abstract interface for all LLM clinical explanation providers."""

    @abstractmethod
    async def generate_explanation(self, prompt_data: Dict) -> Dict:
        """
        Generate a clinical explanation.

        Args:
            prompt_data: Dict containing patient, vitals, prediction data

        Returns:
            {
                "explanation": str,
                "severity": str,
                "clinical_reasoning": str,
                "recommendations": List[str],
                "provider": str,
                "model_name": str,
                "tokens_used": Optional[int],
                "raw_response": dict,
            }
        """
        ...


class MockProvider(LLMProvider):
    """
    Deterministic mock provider for development and academic demonstrations.
    Produces realistic clinical-style explanations without requiring an API key.
    """

    MOCK_EXPLANATIONS = {
        "Normal": {
            "explanation": "The chest X-ray analysis indicates a normal pulmonary appearance with no significant abnormalities detected. The AI model assigned a high confidence to the Normal classification.",
            "severity": "Low",
            "clinical_reasoning": "No infiltrates, consolidations, or pleural effusions identified. Lung fields appear clear. Cardiac silhouette within normal limits.",
            "recommendations": [
                "No immediate radiological intervention required",
                "Continue routine monitoring if symptoms persist",
                "Correlate with clinical presentation and consider repeat imaging if symptoms worsen",
                "Document findings and reassess in 4-6 weeks if clinically indicated",
            ],
        },
        "Pneumonia": {
            "explanation": "The AI model detected radiological features consistent with pneumonia. Consolidation patterns suggest active pulmonary infection requiring prompt clinical management.",
            "severity": "High",
            "clinical_reasoning": "Imaging features suggest alveolar infiltration consistent with bacterial or atypical pneumonia. Clinical correlation with fever, elevated WBC, and productive cough supports this diagnosis.",
            "recommendations": [
                "Initiate empirical antibiotic therapy per local guidelines (community-acquired pneumonia protocol)",
                "Order full blood count, CRP, procalcitonin, and blood cultures before antibiotic initiation",
                "Monitor oxygen saturation closely; supplemental oxygen if SpO2 < 94%",
                "Consider hospital admission if CURB-65 score ≥ 2",
                "Follow-up chest X-ray in 6 weeks to confirm resolution",
            ],
        },
        "COVID-19": {
            "explanation": "Bilateral ground-glass opacities and peripheral infiltrates detected are consistent with COVID-19 pneumonia pattern. These findings require immediate isolation protocols and clinical management.",
            "severity": "High",
            "clinical_reasoning": "Radiological pattern of bilateral peripheral ground-glass opacities is characteristic of COVID-19. Combined with clinical symptoms, this warrants urgent RT-PCR confirmation and infection control measures.",
            "recommendations": [
                "Immediate COVID-19 RT-PCR testing and isolation per institutional protocol",
                "Monitor for clinical deterioration: oxygen requirement, respiratory rate, consciousness",
                "Assess for Remdesivir or Dexamethasone eligibility per current COVID-19 treatment guidelines",
                "Daily monitoring of SpO2, respiratory rate, and inflammatory markers (D-dimer, ferritin, IL-6)",
                "ICU assessment if SpO2 < 90% on supplemental oxygen or respiratory rate > 30/min",
            ],
        },
        "Tuberculosis": {
            "explanation": "Upper lobe infiltrates and/or cavitary lesions consistent with active tuberculosis detected. Immediate public health notification and TB work-up required.",
            "severity": "High",
            "clinical_reasoning": "Upper lobe predominant infiltrates, potential cavitation, and nodular opacities are classic radiological signs of pulmonary tuberculosis. Epidemiological risk factors should be assessed.",
            "recommendations": [
                "Immediate sputum AFB smear × 3 specimens and mycobacterial culture",
                "GeneXpert MTB/RIF rapid molecular testing",
                "Contact tracing and notification to public health authorities",
                "Initiate DOTS (Directly Observed Treatment Short-course) upon confirmation",
                "HIV testing — co-infection significantly impacts management",
                "Strict respiratory isolation until smear-negative",
            ],
        },
    }

    async def generate_explanation(self, prompt_data: Dict) -> Dict:
        predicted_class = prompt_data.get("predicted_class", "Normal")
        mock_data = self.MOCK_EXPLANATIONS.get(
            predicted_class,
            self.MOCK_EXPLANATIONS["Normal"]
        )
        return {
            **mock_data,
            "provider": "mock",
            "model_name": "MockProvider v1.0",
            "tokens_used": None,
            "raw_response": {"mock": True},
        }


class OpenAIProvider(LLMProvider):
    """OpenAI GPT-based clinical explanation provider."""

    async def generate_explanation(self, prompt_data: Dict) -> Dict:
        prompt = CLINICAL_PROMPT_TEMPLATE.format(**prompt_data)
        headers = {
            "Authorization": f"Bearer {settings.OPENAI_API_KEY}",
            "Content-Type": "application/json",
        }
        payload = {
            "model": settings.OPENAI_MODEL,
            "messages": [
                {"role": "system", "content": "You are a clinical decision support AI. Always respond in valid JSON."},
                {"role": "user", "content": prompt},
            ],
            "max_tokens": 1000,
            "temperature": 0.3,
            "response_format": {"type": "json_object"},
        }
        async with httpx.AsyncClient(timeout=30) as client:
            response = await client.post(
                "https://api.openai.com/v1/chat/completions",
                headers=headers,
                json=payload,
            )
            response.raise_for_status()
            data = response.json()

        content = data["choices"][0]["message"]["content"]
        parsed = json.loads(content)
        tokens_used = data.get("usage", {}).get("total_tokens")

        return {
            "explanation": parsed.get("explanation", ""),
            "severity": parsed.get("severity", "Moderate"),
            "clinical_reasoning": parsed.get("clinical_reasoning", ""),
            "recommendations": parsed.get("recommendations", []),
            "provider": "openai",
            "model_name": settings.OPENAI_MODEL,
            "tokens_used": tokens_used,
            "raw_response": data,
        }


class LocalLLMProvider(LLMProvider):
    """OpenAI-compatible local LLM provider (Ollama, LM Studio, etc.)."""

    async def generate_explanation(self, prompt_data: Dict) -> Dict:
        prompt = CLINICAL_PROMPT_TEMPLATE.format(**prompt_data)
        payload = {
            "model": "llama3.2",
            "messages": [
                {"role": "user", "content": prompt}
            ],
            "stream": False,
        }
        async with httpx.AsyncClient(timeout=60) as client:
            response = await client.post(
                f"{settings.LOCAL_LLM_URL}/api/chat",
                json=payload,
            )
            response.raise_for_status()
            data = response.json()

        content = data.get("message", {}).get("content", "{}")
        # Strip markdown code fences if present
        if "```json" in content:
            content = content.split("```json")[1].split("```")[0].strip()
        parsed = json.loads(content)

        return {
            "explanation": parsed.get("explanation", ""),
            "severity": parsed.get("severity", "Moderate"),
            "clinical_reasoning": parsed.get("clinical_reasoning", ""),
            "recommendations": parsed.get("recommendations", []),
            "provider": "local",
            "model_name": "local-llm",
            "tokens_used": None,
            "raw_response": data,
        }


def get_llm_provider() -> LLMProvider:
    """
    Factory function: returns the configured LLM provider.
    Change LLM_PROVIDER in .env to switch providers.
    """
    provider_map = {
        "openai": OpenAIProvider,
        "local": LocalLLMProvider,
        "mock": MockProvider,
    }
    cls = provider_map.get(settings.LLM_PROVIDER, MockProvider)
    logger.info(f"Using LLM provider: {settings.LLM_PROVIDER} ({cls.__name__})")
    return cls()
